### ISSUE TITLE
IndexOutOfBoundsException в Field.cs:19 для некорректных Location переданых в FieldView

### ISSUE THREAD

**Issue by wingrime** [DQKrait/SpurRoguelike#3]
FieldView.cs:13 содержит проверку на некорректные значения Location, проверка должна
срабатывать когда Field[Location] возвращает  null, но проверка не работает так как Field.cs:19 не проверяет индекс и как следствие, вызывается исключение

**Comment by DQKrait** [comment]
> FieldView.cs:13 содержит проверку на некорректные значения Location

Это не так. Проверка нужна, чтобы вернуть CellType.Empty, если field == null. Это общее свойство всех View - их проперти не должны кидать исключения, если View смотрит на null.
В случае же индексации некорректным Location'ом как FieldView, так и Field, должно кидаться исключение.
